# Copyright (c) 2017 Dell Inc. or its subsidiaries.  All Rights Reserved.
# Dell EMC Confidential/Proprietary Information

version: '2'

services:

  fru-paqx:
    image: cpsd-fru-paqx-service
    container_name: symphony-fru-paqx
    network_mode: "host"

